### ISSUE TITLE
Using asciidoctor for documentation

### ISSUE THREAD

**Issue by vechocho** [gbif/hp-ecuador#1]
I was trying to write some documentation for our users and in the [_conf.yml for the base demo](https://github.com/gbif/jekyll-hp-base-theme/blob/master/_config.yml) there is this text:

```
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  ext: asciidoc
``` 

is this related for writing documentation or only markdown is valid?
